fix: missing fft header include
I needed to include `fft.h` in `studio.c` to get this fork to build on
Mac. Without this I was getting the following errors:

```
error: implicit declaration of function 'FFT_Create' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        FFT_Create();
error: implicit declaration of function 'FFT_EnumerateDevices' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        FFT_EnumerateDevices(print_fft_devices, NULL);
```